### ISSUE TITLE
Part doesn't like the "${Internal.Entry.Current.Directory}" in paths

### ISSUE THREAD

**Issue by jfmonteil** [Pentaho-SE-EMEA-APAC/part#194] opened 2018-09-13 15:40 UTC
Caused by: java.net.URISyntaxException: Illegal character in path at index 46: http://localhost:8080/pentaho/api/repo/files/${Internal.Entry.Current.Directory}%3AGarbageData.ktr/download?withManifest=false

**Comment by adamfowleruk** [comment] 2018-09-13 18:48
Duplicate of #188

**Closed by adamfowleruk** 2018-09-13 18:48 UTC
Labels: duplicate
